Revert "Drop pkg-config build dependency"
This reverts commit 23df143971010eee20a3535a4e701b8cca25cf6e.

While pkg-config is no longer necessary to create and install the .pc
files, it is still needed to build the test programs.  Without, the
linker fails with an error message:

/usr/bin/ld: ../obj-test/background.o: undefined reference to symbol 'acs_map@@NCURSES_TINFO_5.0.19991023'

This problem had been hidden by the existence of
/usr/bin/ncursesw5-config which would have been used as fallback, but
that file is no longer guaranteed to exist.